import "@styles/globals.css";
import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";

import { cn } from "@utils/tw";

import ContainerFully from "@shared/layouts/main/container-fully";
import FrameFully from "@shared/layouts/main/screen-fully";

import Providers from "./provider";

const nextFont = DM_Mono({
  display: "swap",
  weight: ["300", "400", "500"],
  preload: false,
});

export const metadata: Metadata = {
  title: "Austin Vu Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/logo.png" sizes="any" />
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          nextFont.className,
        )}
        suppressHydrationWarning
      >
        <Providers>
          <ContainerFully>
            <FrameFully>{children}</FrameFully>
          </ContainerFully>
        </Providers>
      </body>
    </html>
  );
}
