import "@styles/globals.css";
import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";

import MainContainer from "@shared/layouts/main/container";
import Providers from "./provider";

const nextFont = DM_Mono({
  display: "swap",
  weight: ["300", "400", "500"],
  preload: true,
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Austin Vu Web",
  description: "Generated by create next app",
  icons: [
    {
      rel: 'apple-touch-icon',
      url: '/logo.png',
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '32x32',
      url: '/logo.png',
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '16x16',
      url: '/logo.png',
    },
    {
      rel: 'icon',
      url: 'logo.png',
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="scroll-smooth antialiased focus:scroll-auto"
    >
      <body className={nextFont.className}>
        <Providers>
          <MainContainer>
            {children}
          </MainContainer>
        </Providers>
      </body>
    </html>
  );
}
