import { useGLTF } from "@react-three/drei";
import { memo } from "react";

interface ModelClassRoomProps {
  position: [number, number, number];
  scale: [number, number, number];
  [key: string]: any;
}

export const ModelClassRoom = memo(
  ({ position, scale, ...props }: ModelClassRoomProps) => {
    const { nodes, materials } = useGLTF(
      "/compressed_1729262859516_japanese_classroom.glb",
    );
    return (
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BancaEstudiante_14pCylinder10_BancaEstudiante_14phong1_0
              .geometry
          }
          material={materials.BancaEstudiante_14phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BancaEstudiante_14pCylinder13_BancaEstudiante_14phong1_0
              .geometry
          }
          material={materials.BancaEstudiante_14phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BancaEstudiante_14pCube9_BancaEstudiante_14phong1_0.geometry
          }
          material={materials.BancaEstudiante_14phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BancaEstudiante_14pCylinder12_BancaEstudiante_14phong1_0
              .geometry
          }
          material={materials.BancaEstudiante_14phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BancaEstudiante_14pCylinder11_BancaEstudiante_14phong1_0
              .geometry
          }
          material={materials.BancaEstudiante_14phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BancaEstudiante_14pCylinder9_BancaEstudiante_14phong1_0
              .geometry
          }
          material={materials.BancaEstudiante_14phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BancaEstudiante_14polySurface9_BancaEstudiante_14phong1_0
              .geometry
          }
          material={materials.BancaEstudiante_14phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BancaEstudiante_14pCube8_BancaEstudiante_14phong1_0.geometry
          }
          material={materials.BancaEstudiante_14phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BancaEstudiante_14pCube7_BancaEstudiante_14phong1_0.geometry
          }
          material={materials.BancaEstudiante_14phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BancaEstudiante_14pCube10_BancaEstudiante_14phong1_0.geometry
          }
          material={materials.BancaEstudiante_14phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane4_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface27_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface12_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface16_MuroDetalle_0_1.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane5_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface12_MuroDetalle_0_1.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface16_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane12_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface66_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface70_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface73_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface72_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface20_Pizarrones1_0.geometry}
          material={materials.Pizarrones1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface19_Pizarrones1_0.geometry}
          material={materials.Pizarrones1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface17_Pizarrones1_0.geometry}
          material={materials.Pizarrones1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface18_Pizarrones1_0_1.geometry}
          material={materials.Pizarrones1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_LockerLampara_0.geometry}
          material={materials.LockerLampara}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BaseFoco_LockerLampara_0.geometry}
          material={materials.LockerLampara}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tubo_LockerLampara_0.geometry}
          material={materials.LockerLampara}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Foco_LockerLampara_0.geometry}
          material={materials.LockerLampara}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SeguroP1_LockerLampara_0.geometry}
          material={materials.LockerLampara}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SeguroP2_LockerLampara_0.geometry}
          material={materials.LockerLampara}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CuerpoP1_LockerLampara_0.geometry}
          material={materials.LockerLampara}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CuerpoP2_LockerLampara_0.geometry}
          material={materials.LockerLampara}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_LockerLampara_0.geometry}
          material={materials.LockerLampara}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube7_phong2_0.geometry}
          material={materials.phong2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube40_lambert42_0.geometry}
          material={materials.lambert42}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube39_lambert42_0.geometry}
          material={materials.lambert42}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder16_lambert42_0.geometry}
          material={materials.lambert42}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube46_lambert42_0.geometry}
          material={materials.lambert42}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube48_lambert42_0.geometry}
          material={materials.lambert42}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube53_lambert42_0.geometry}
          material={materials.lambert42}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface26_StingrayPBS3_0.geometry}
          material={materials.StingrayPBS3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface30_MurosLaterales_0.geometry}
          material={materials.MurosLaterales}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane3_MuroDetalle_0.geometry}
          material={materials.MuroDetalle}
          position={[-9.376, 0, -58.122]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface22_StingrayPBS2_0.geometry}
          material={materials.StingrayPBS2}
          position={[-35.972, 12, -18]}
          scale={[96, 24, 48]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface66_lambert28_0.geometry}
          material={materials.lambert28}
          position={[-35.972, 11.984, -18]}
          scale={[96, 24, 48]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TarimaUp_Tarima1_0.geometry}
          material={materials.Tarima1}
          position={[0, 0.189, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface18_Pizarrones1_0.geometry}
          material={materials.Pizarrones1}
          position={[0.096, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LibreroCH_Libreros1_0.geometry}
          material={materials.Libreros1}
          position={[0, 0.146, 0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder8_StingrayPBS9_0.geometry}
          material={materials.StingrayPBS9}
          position={[-82.484, 19.946, -27.436]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[1.413, 0.35, 1.413]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube8_phong2_0.geometry}
          material={materials.phong2}
        />
      </group>
    );
  },
);
